### PR TITLE
Allow to use deprecated `connect()` for Rust 1.1 support

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Currently this library is still targeting rust 1.1, so these methods can't be renamed just yet, but perhaps an `#[allow(deprecated)]` annotation could be added?

**Comment by zetok** [comment]
Well, I guess I'll morph this PR to do that.
(not ~now though, I'll do that probably within a day)

**Comment by zetok** [comment]
ok, done.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
